
package com.qbe.cotizador.servicios.smartwork.workflow;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "ExternalService", targetNamespace = "http://smartwork.com.ec/", wsdlLocation = "http://10.10.21.40:8080/BPMServer/ExternalService.asmx?WSDL")
public class ExternalService
    extends Service
{

    private final static URL EXTERNALSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.qbe.cotizador.servicios.smartwork.workflow.ExternalService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.qbe.cotizador.servicios.smartwork.workflow.ExternalService.class.getResource(".");
            url = new URL(baseUrl, "http://10.10.21.40:8080/BPMServer/ExternalService.asmx?WSDL");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://10.10.21.40:8080/BPMServer/ExternalService.asmx?WSDL', retrying as a local file");
            logger.warning(e.getMessage());
        }
        EXTERNALSERVICE_WSDL_LOCATION = url;
    }

    public ExternalService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ExternalService() {
        super(EXTERNALSERVICE_WSDL_LOCATION, new QName("http://smartwork.com.ec/", "ExternalService"));
    }

    /**
     * 
     * @return
     *     returns ExternalServiceSoap
     */
    @WebEndpoint(name = "ExternalServiceSoap")
    public ExternalServiceSoap getExternalServiceSoap() {
        return super.getPort(new QName("http://smartwork.com.ec/", "ExternalServiceSoap"), ExternalServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ExternalServiceSoap
     */
    @WebEndpoint(name = "ExternalServiceSoap")
    public ExternalServiceSoap getExternalServiceSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://smartwork.com.ec/", "ExternalServiceSoap"), ExternalServiceSoap.class, features);
    }

}
