
package com.qbe.cotizador.servicios.QBE.cliente;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "WebServiceCotizadorImplService", targetNamespace = "http://cotizador.implementacion.servicios.qbe.com/", wsdlLocation = "http://10.10.21.116/servicios/cotizador?wsdl")
public class WebServiceCotizadorImplService
    extends Service
{

    private final static URL WEBSERVICECOTIZADORIMPLSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(WebServiceCotizadorImplService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = WebServiceCotizadorImplService.class.getResource(".");
            //url = new URL(baseUrl, "http://cotizador.qbe.com.ec:8080/servicios/cotizador?wsdl");
            url = new URL(baseUrl, "http://10.10.21.116:8080/servicios/cotizador?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://10.10.21.116/servicios/cotizador?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        WEBSERVICECOTIZADORIMPLSERVICE_WSDL_LOCATION = url;
    }

    public WebServiceCotizadorImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WebServiceCotizadorImplService() {
        super(WEBSERVICECOTIZADORIMPLSERVICE_WSDL_LOCATION, new QName("http://cotizador.implementacion.servicios.qbe.com/", "WebServiceCotizadorImplService"));
    }

    /**
     * 
     * @return
     *     returns WebServiceCotizadorInterface
     */
    @WebEndpoint(name = "WebServiceCotizadorImplPort")
    public WebServiceCotizadorInterface getWebServiceCotizadorImplPort() {
        return super.getPort(new QName("http://cotizador.implementacion.servicios.qbe.com/", "WebServiceCotizadorImplPort"), WebServiceCotizadorInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WebServiceCotizadorInterface
     */
    @WebEndpoint(name = "WebServiceCotizadorImplPort")
    public WebServiceCotizadorInterface getWebServiceCotizadorImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://cotizador.implementacion.servicios.qbe.com/", "WebServiceCotizadorImplPort"), WebServiceCotizadorInterface.class, features);
    }

}
