
package com.qbe.cotizador.servicios.recargoSC.cliente;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "InquiredServiceInterface", targetNamespace = "http://interfaces.webservice.tandiesb.tandicorp.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface InquiredServiceInterface {


    /**
     * 
     * @param prima
     * @param identificacion
     * @return
     *     returns java.lang.Double
     */
    @WebMethod
    @WebResult(name = "RecargoSeguroAgricola", targetNamespace = "")
    @RequestWrapper(localName = "consultarRecargoSeguroAgricola", targetNamespace = "http://interfaces.webservice.tandiesb.tandicorp.com/", className = "com.tandicorp.tandiesb.webservice.interfaces.ConsultarRecargoSeguroAgricola")
    @ResponseWrapper(localName = "consultarRecargoSeguroAgricolaResponse", targetNamespace = "http://interfaces.webservice.tandiesb.tandicorp.com/", className = "com.tandicorp.tandiesb.webservice.interfaces.ConsultarRecargoSeguroAgricolaResponse")
    public Double consultarRecargoSeguroAgricola(
        @WebParam(name = "identificacion", targetNamespace = "")
        String identificacion,
        @WebParam(name = "prima", targetNamespace = "")
        Double prima);

}
