
package com.qbe.cotizador.servicios.recargoSC.cliente;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "InquiredServiceInterfaceService", targetNamespace = "http://interfaces.webservice.tandiesb.tandicorp.com/", wsdlLocation = "http://10.10.10.86:9193/webservices/ensurance/inquire?wsdl")
public class InquiredServiceInterfaceService
    extends Service
{

    private final static URL INQUIREDSERVICEINTERFACESERVICE_WSDL_LOCATION;
    private final static WebServiceException INQUIREDSERVICEINTERFACESERVICE_EXCEPTION;
    private final static QName INQUIREDSERVICEINTERFACESERVICE_QNAME = new QName("http://interfaces.webservice.tandiesb.tandicorp.com/", "InquiredServiceInterfaceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://10.10.10.86:9193/webservices/ensurance/inquire?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        INQUIREDSERVICEINTERFACESERVICE_WSDL_LOCATION = url;
        INQUIREDSERVICEINTERFACESERVICE_EXCEPTION = e;
    }

    public InquiredServiceInterfaceService() {
        super(__getWsdlLocation(), INQUIREDSERVICEINTERFACESERVICE_QNAME);
    }

    public InquiredServiceInterfaceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), INQUIREDSERVICEINTERFACESERVICE_QNAME, features);
    }

    public InquiredServiceInterfaceService(URL wsdlLocation) {
        super(wsdlLocation, INQUIREDSERVICEINTERFACESERVICE_QNAME);
    }

    public InquiredServiceInterfaceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, INQUIREDSERVICEINTERFACESERVICE_QNAME, features);
    }

    public InquiredServiceInterfaceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public InquiredServiceInterfaceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns InquiredServiceInterface
     */
    @WebEndpoint(name = "InquiredServiceInterfacePort")
    public InquiredServiceInterface getInquiredServiceInterfacePort() {
        return super.getPort(new QName("http://interfaces.webservice.tandiesb.tandicorp.com/", "InquiredServiceInterfacePort"), InquiredServiceInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns InquiredServiceInterface
     */
    @WebEndpoint(name = "InquiredServiceInterfacePort")
    public InquiredServiceInterface getInquiredServiceInterfacePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://interfaces.webservice.tandiesb.tandicorp.com/", "InquiredServiceInterfacePort"), InquiredServiceInterface.class, features);
    }

    private static URL __getWsdlLocation() {
        if (INQUIREDSERVICEINTERFACESERVICE_EXCEPTION!= null) {
            throw INQUIREDSERVICEINTERFACESERVICE_EXCEPTION;
        }
        return INQUIREDSERVICEINTERFACESERVICE_WSDL_LOCATION;
    }

}
