
package com.qbe.cotizador.servicios.QBE.emisionWS;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "EmisionQbeLink", targetNamespace = "http://wsqbelink.servicios.tandi.com/", wsdlLocation = "http://10.10.10.177:8084/ensurance/EmisionQbeLink?wsdl")
public class EmisionQbeLink_Service
    extends Service
{

    private final static URL EMISIONQBELINK_WSDL_LOCATION;
    private final static WebServiceException EMISIONQBELINK_EXCEPTION;
    private final static QName EMISIONQBELINK_QNAME = new QName("http://wsqbelink.servicios.tandi.com/", "EmisionQbeLink");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            //url = new URL("http://10.10.21.18/ensurance/EmisionQbeLink?wsdl");
            url = new URL("http://200.93.229.178:8087/ensurance/EmisionQbeLink?wsdl"); // Pruebas 
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        EMISIONQBELINK_WSDL_LOCATION = url;
        EMISIONQBELINK_EXCEPTION = e;
    }

    public EmisionQbeLink_Service() {
        super(__getWsdlLocation(), EMISIONQBELINK_QNAME);
    }

    public EmisionQbeLink_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), EMISIONQBELINK_QNAME, features);
    }

    public EmisionQbeLink_Service(URL wsdlLocation) {
        super(wsdlLocation, EMISIONQBELINK_QNAME);
    }

    public EmisionQbeLink_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, EMISIONQBELINK_QNAME, features);
    }

    public EmisionQbeLink_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EmisionQbeLink_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns EmisionQbeLink
     */
    @WebEndpoint(name = "EmisionQbeLinkPort")
    public EmisionQbeLink getEmisionQbeLinkPort() {
        return super.getPort(new QName("http://wsqbelink.servicios.tandi.com/", "EmisionQbeLinkPort"), EmisionQbeLink.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EmisionQbeLink
     */
    @WebEndpoint(name = "EmisionQbeLinkPort")
    public EmisionQbeLink getEmisionQbeLinkPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://wsqbelink.servicios.tandi.com/", "EmisionQbeLinkPort"), EmisionQbeLink.class, features);
    }

    private static URL __getWsdlLocation() {
        if (EMISIONQBELINK_EXCEPTION!= null) {
            throw EMISIONQBELINK_EXCEPTION;
        }
        return EMISIONQBELINK_WSDL_LOCATION;
    }

}
